# Generated by Django 2.2.2 on 2020-01-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(null=True, to='news.Category'),
        ),
    ]
